Phpcs fixes
Automattic/safe-report-comments pull request #7
Opened 2021-06-02 23:45 UTC by trepmal

General sprucing up.

 - escaping
 - formatting
 - better isset checks
 - whitespace trimming

2021-06-02 23:52 UTC, trepmal commented
No null coalescing operator if we want to support PHP<7
https://www.php.net/manual/en/migration70.new-features.php#migration70.new-features.null-coalesce-op

2021-06-02 23:59 UTC, trepmal commented
Adding license info in here just to get ahead of merge conflict.

2021-06-03 16:16 UTC, trepmal commented
PHP 5 tests removed in #8

2021-06-15 10:03 UTC, GaryJones requested changes

2021-06-15 10:03 UTC, GaryJones commented on safe-report-comments.php
> +			$remote_addr = filter_var( isset( $_SERVER['REMOTE_ADDR'] ) ? $_SERVER['REMOTE_ADDR'] : '', 'FILTER_VALIDATE_IP' );
Consider changing to use `filter_input()`, which should then move away from needing the PHPCS ignore as well.

2021-06-15 10:03 UTC, GaryJones commented on safe-report-comments.php
> +			$remote_addr = filter_var( isset( $_SERVER['REMOTE_ADDR'] ) ? $_SERVER['REMOTE_ADDR'] : '', 'FILTER_VALIDATE_IP' );
As above.

2021-06-15 10:03 UTC, GaryJones commented on safe-report-comments.php
> +			if ( ! isset( $_REQUEST[ 'comment_id' ] ) || empty( $_REQUEST[ 'comment_id' ] ) || (int) $_REQUEST[ 'comment_id' ] != $_REQUEST[ 'comment_id' ] ) {
No need for the `isset()` check if it's followed by `empty()` - `empty()` won't give any notice or warning if it's not set.

2021-06-17 09:06 UTC, GaryJones approved these changes

2021-06-17 16:01 UTC, merged